// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package database

import (
	"context"
)

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO adminUsers
(
    user_id
) VALUES (
    $1
) RETURNING id, user_id, created_at
`

func (q *Queries) CreateAdminUser(ctx context.Context, userID int64) (*Adminuser, error) {
	row := q.db.QueryRow(ctx, createAdminUser, userID)
	var i Adminuser
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return &i, err
}

const deleteAdminUser = `-- name: DeleteAdminUser :one
DELETE FROM adminUsers
WHERE user_id = $1  RETURNING id, user_id, created_at
`

func (q *Queries) DeleteAdminUser(ctx context.Context, userID int64) (*Adminuser, error) {
	row := q.db.QueryRow(ctx, deleteAdminUser, userID)
	var i Adminuser
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return &i, err
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT id, user_id, created_at FROM adminUsers WHERE user_id = $1
`

func (q *Queries) GetAdminUser(ctx context.Context, userID int64) (*Adminuser, error) {
	row := q.db.QueryRow(ctx, getAdminUser, userID)
	var i Adminuser
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return &i, err
}
