// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employees.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees
(
    user_id,
    job_title,
    country,
    salary,
    created_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, job_title, country, salary, created_at
`

type CreateEmployeeParams struct {
	UserID    int64            `json:"user_id"`
	JobTitle  string           `json:"job_title"`
	Country   string           `json:"country"`
	Salary    pgtype.Numeric   `json:"salary"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (*Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.UserID,
		arg.JobTitle,
		arg.Country,
		arg.Salary,
		arg.CreatedAt,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobTitle,
		&i.Country,
		&i.Salary,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteEmployeeByUserId = `-- name: DeleteEmployeeByUserId :one
DELETE FROM employees WHERE user_id = $1 RETURNING id, user_id, job_title, country, salary, created_at
`

func (q *Queries) DeleteEmployeeByUserId(ctx context.Context, userID int64) (*Employee, error) {
	row := q.db.QueryRow(ctx, deleteEmployeeByUserId, userID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobTitle,
		&i.Country,
		&i.Salary,
		&i.CreatedAt,
	)
	return &i, err
}

const getEmployeByuserById = `-- name: GetEmployeByuserById :one
SELECT id, user_id, job_title, country, salary, created_at FROM employees WHERE user_id = $1
`

func (q *Queries) GetEmployeByuserById(ctx context.Context, userID int64) (*Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeByuserById, userID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobTitle,
		&i.Country,
		&i.Salary,
		&i.CreatedAt,
	)
	return &i, err
}

const updateEmployeeByUserId = `-- name: UpdateEmployeeByUserId :one
UPDATE employees
SET 
    job_title  = $2,
    country    = $3,
    salary     = $4
WHERE user_id = $1
RETURNING id, user_id, job_title, country, salary, created_at
`

type UpdateEmployeeByUserIdParams struct {
	UserID   int64          `json:"user_id"`
	JobTitle string         `json:"job_title"`
	Country  string         `json:"country"`
	Salary   pgtype.Numeric `json:"salary"`
}

func (q *Queries) UpdateEmployeeByUserId(ctx context.Context, arg UpdateEmployeeByUserIdParams) (*Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployeeByUserId,
		arg.UserID,
		arg.JobTitle,
		arg.Country,
		arg.Salary,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobTitle,
		&i.Country,
		&i.Salary,
		&i.CreatedAt,
	)
	return &i, err
}
