// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Adminuser struct {
	ID        int32            `json:"id"`
	UserID    int64            `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Employee struct {
	ID        int32            `json:"id"`
	UserID    int64            `json:"user_id"`
	JobTitle  string           `json:"job_title"`
	Country   string           `json:"country"`
	Salary    pgtype.Numeric   `json:"salary"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID           int32            `json:"id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
