// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (*Employee, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteEmployeeByUserId(ctx context.Context, userID int64) (*Employee, error)
	GetAvgSalaryPerJobTitle(ctx context.Context, jobTitle string) (*GetAvgSalaryPerJobTitleRow, error)
	GetEmployeByuserById(ctx context.Context, userID int64) (*Employee, error)
	GetSalaryMetricsByCountry(ctx context.Context, country string) (*GetSalaryMetricsByCountryRow, error)
	GetUserById(ctx context.Context, id int32) (*User, error)
	GetUserByName(ctx context.Context, username string) (*User, error)
	UpdateEmployeeByUserId(ctx context.Context, arg UpdateEmployeeByUserIdParams) (*Employee, error)
}

var _ Querier = (*Queries)(nil)
